### ISSUE TITLE
Criar Slack para o time e adicionar integrações

### ISSUE THREAD

**Issue by icaropires** [CodeCollegeGroup/CodeCollege#27]
- [x] criar workspace no slack
- [x] adicionar email de todo mundo
- [x] integrar github
- [x] integrar travis
- [x] integrar google drive
- [x] integrar codeclimate
- [x] integrar zenhub

**Comment by icaropires** [comment]
@mendesiasmin não to conseguindo integrar o zenhub e o codeclimate (o codeclimate ainda precisa integrar repositório) porque não aparece nos meus repositórios, acho que vai você vai ter que fazer isso :grimacing:

**Comment by mendesiasmin** [comment]
@icaropires Eu habilitei o ZenHub, mas como nunca usei ele, não sei se precisa fazer alguma configuração a mais.
